#!/usr/bin/env python3
"""Download the Google Fonts used by the site and generate local @font-face CSS.

Run with:
    python3 scripts/sync_fonts.py
"""

from __future__ import annotations

import hashlib
import re
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "static/fonts"
CSS_OUTPUT = ROOT / "src/routes/fonts.generated.css"
FONT_CSS_URL = (
	"https://fonts.googleapis.com/css2?"
	"family=Geist:ital,wght@0,100..900;1,100..900&"
	"family=Instrument+Serif:ital@0;1&display=swap"
)
USER_AGENT = (
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
	"AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36"
)
URL_PATTERN = re.compile(r"https://fonts\.gstatic\.com/[^)]+?\.woff2")


def download(url: str) -> bytes:
	request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
	with urllib.request.urlopen(request, timeout=30) as response:
		return response.read()


def main() -> None:
	OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
	css = download(FONT_CSS_URL).decode("utf-8")
	font_urls = list(dict.fromkeys(URL_PATTERN.findall(css)))
	if not font_urls:
		raise SystemExit("Google Fonts returned no WOFF2 URLs")

	for url in font_urls:
		filename = f"{hashlib.sha256(url.encode()).hexdigest()[:12]}.woff2"
		output = OUTPUT_DIR / filename
		if not output.exists():
			temporary = output.with_suffix(".tmp.woff2")
			temporary.write_bytes(download(url))
			temporary.replace(output)
		css = css.replace(url, f"/fonts/{filename}")

	header = "/* Generated by scripts/sync_fonts.py. Do not edit by hand. */\n"
	CSS_OUTPUT.write_text(header + css.strip() + "\n", encoding="utf-8")
	font_bytes = sum(path.stat().st_size for path in OUTPUT_DIR.glob("*.woff2"))
	print(f"Synced {len(font_urls)} local font files ({font_bytes / 1024:.0f} KiB)")


if __name__ == "__main__":
	main()
